###consull服务端口号
server:
  port: 8006
  ssl:
    enabled: false

spring:
  application:
    name: MicroService-Service
  ###consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
